#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading PHP-FPM configuration..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
config_nginx

#=================================================
# UPGRADE SOURCE FILE
#=================================================
ynh_script_progression "Upgrading source files..."

pear_cmd="$install_dir/pear/pear -c $install_dir/pear.conf"
$pear_cmd channel-update pear.horde.org
$pear_cmd upgrade -R $install_dir -a -B -c pear.horde.org || true

#=================================================
# PATCH APPLICATION
#=================================================
ynh_script_progression "Patching application..."

patch_app

#=================================================
# CONFIGURE HORDE
#=================================================
ynh_script_progression "Configuring application..."

config_horde

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Protecting directory..."

set_permission

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

ynh_config_add_logrotate "$install_dir/horde"  www-data/horde
ynh_config_add_logrotate "$install_dir/horde/services"  www-data/horde
ynh_config_add_logrotate "$install_dir/horde/services/portal"  www-data/horde

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
